name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install
        run: |
          npm install
          npm install -g firebase-tools
      - name: lint and test
        run: |
          npm run lint
          npm test
          - name: Check current directory and list files
          run: |
            # 現在のディレクトリを表示
            pwd
            
            # リポジトリのルートディレクトリの内容をリスト表示
            ls -la
            
            # "sk32" フォルダ内の内容をリスト表示
            ls -la ./sk32

            # "sk32" フォルダの中で、package.json を探す
            find ./sk32 -name "package.json"

      - run: npm run build:prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SK32_APP }}
          channelId: live
          projectId: sk32-app
